name: stud_advice
description: Frontend for Stud'Advice application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.13.0
  google_fonts: ^6.1.0
  logger: ^2.0.2+1
  get_it: ^7.6.4
  english_words: ^4.0.0
  intl: ^0.18.1
  country_picker: ^2.0.22
  dio: ^5.3.3
  flutter_typeahead: ^4.8.0
  dropdown_search: ^5.0.6
  select_dialog: ^2.0.1
  connectivity_plus: ^5.0.1
  awesome_dialog: ^3.1.0
  jiffy: ^6.2.1
  search_choices: ^2.2.7
#  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/images/login/


#flutter_native_splash:
##  Ajouter une image avec le slogan de l'application, made easy for students
#  image: assets/images/common/raven_image.png
#  color: "#42a5f5"
#  android: true
#  ios: true
#  dark: true